import random

print("Hi buddy")

Userin = input("Enter your username here:")

Userin_choice = input("Do you want a random password generated by AI? (Yep/Nope): ").strip().lower()
if Userin_choice == "yep":
    Chb = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
    Chm = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n']
    Chn = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
    Chs = ['!', '@', '#', '$', '%', '^', '&', '*', '-', '/']
    Choice=random.choice(Chb)
    Choice1 = random.choice(Chm)
    Choice2 = random.choice(Chn)
    Choice3 = random.choice(Chs)
    Choice4 = random.choice(Chb)
    Choice5 = random.choice(Chm)
    Choice6 = random.choice(Chn)
    Choice7 = random.choice(Chs)
    Choice8 = random.choice(Chb)
    Choice9 = random.choice(Chm)
    Choice10 = random.choice(Chn)
    Choice11 = random.choice(Chs)

    print(Choice + Choice1 + Choice2 + Choice3 + Choice4 + Choice5 + Choice6 + Choice7 + Choice8 + Choice9 + Choice10 + Choice11)

elif Userin_choice == "nope":
    pass
else:
    print("Invalid choice. Kindly enter 'Yep' or 'Nope'.")
